export const GalleryData = [
  {
      id:1,
      titile:"car",
      image:"../assets/images/kilifi1.jpg"
  },
  {
      id:2,
      titile:"car",
      image:"../assets/images/kilifi7.jpg"
  },
  {
      id:3,
      titile:"car",
      image:"../assets/images/kilifi8.jpg"
  },
  {
      id:4,
      titile:"car",
      url:"../assets/images/9.jpg"
  },
  {
      id:5,
      titile:"bike",
      image:"../assets/images/kilifi10.jpg"
  },
  {
      id:6,
      titile:"bike",
      image:"../assets/images/kilifi13.jpg"
  },
  {
      id:7,
      titile:"cycle",
      image:"../assets/images/kilifi12.jpg"
  },
  {
      id:8,
      titile:"cycle",
      image:"../assets/images/kilifi11.jpg"
  },
]